export {default as Register} from './Register'
export {default as Login} from './Login'
export {default as Profile} from './View'
export {default as Welcome} from './Welcome'
export {default as RequestReset} from './RequestReset'
export {default as Reset} from './Reset'
